site_name: Semester Portfolio
site_description: Min l√¶ringsportfolio for AI, ML og Software Arkitektur

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top

nav:
  - Forside: index.md

  - Blog:
      - AI & ML blog: "Blog/AI-ML/index.md"
      - Software Arkitektur blog: "Blog/Software-arkitektur-blog/index.md"

  - Semester:
      - Velkomst: "Semester/Index.md"
      - AI & ML: "Semester/AI-ML/index.md"
      - Software Arkitektur & Design Patterns: "Semester/Software-arkitektur-projekter/index.md"
      - Shared: "Semester/Shared/index.md"
