site_name: Semester Portfolio
site_description: Min l√¶ringsportfolio for AI, ML og Software Arkitektur
site_url: https://uyscutty.github.io/semester_portfolio/
use_directory_urls: true


theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top

nav:
  - Forside: index.md

  - Blog:
      - AI & ML blog: blog/ai-ml-blog/index.md
      - Software Arkitektur blog: blog/software-arkitektur-blog/index.md

  - Semester:
      - Velkomst: semester/index.md
      - AI & ML: semester/ai-ml/index.md
      - Software Arkitektur & Design Patterns: semester/software-arkitektur-projekter/index.md
      - Shared: semester/shared/index.md
